import type { OrganizationRole, ShowRole } from "@/lib/db/schema/permissions";

// All possible permissions in the system
export const PERMISSIONS = {
  // Organization-level permissions
  ORG_MANAGE_BILLING: "org:manage_billing",
  ORG_TRANSFER_OWNERSHIP: "org:transfer_ownership",
  ORG_MANAGE_MEMBERS: "org:manage_members",
  ORG_MANAGE_SETTINGS: "org:manage_settings",
  ORG_CREATE_SHOWS: "org:create_shows",
  ORG_VIEW_ALL_SHOWS: "org:view_all_shows",
  ORG_DELETE_SHOWS: "org:delete_shows",

  // Show-level permissions
  SHOW_VIEW: "show:view",
  SHOW_EDIT: "show:edit",
  SHOW_DELETE: "show:delete",
  SHOW_MANAGE_STAFF: "show:manage_staff",

  // Casting permissions
  CASTING_VIEW: "casting:view",
  CASTING_EDIT: "casting:edit",
  CASTING_MAKE_DECISIONS: "casting:make_decisions",

  // Audition permissions
  AUDITIONS_VIEW: "auditions:view",
  AUDITIONS_EDIT: "auditions:edit",
  AUDITIONS_MANAGE: "auditions:manage",

  // Schedule permissions
  SCHEDULE_VIEW: "schedule:view",
  SCHEDULE_EDIT: "schedule:edit",
  SCHEDULE_MANAGE: "schedule:manage",

  // Notes permissions - department specific
  NOTES_VIEW_ALL: "notes:view_all",
  NOTES_PRODUCTION: "notes:production",
  NOTES_LIGHTING: "notes:lighting",
  NOTES_SOUND: "notes:sound",
  NOTES_COSTUME: "notes:costume",
  NOTES_SCENIC: "notes:scenic",
  NOTES_PROPS: "notes:props",
  NOTES_HAIR_MAKEUP: "notes:hair_makeup",
  NOTES_CHOREOGRAPHY: "notes:choreography",
  NOTES_DRAMATURG: "notes:dramaturg",
  NOTES_AD: "notes:ad",

  // Budget permissions
  BUDGET_VIEW: "budget:view",
  BUDGET_EDIT: "budget:edit",
  BUDGET_MANAGE: "budget:manage",
  BUDGET_PROPS: "budget:props",

  // Communication permissions
  COMMUNICATION_SEND: "communication:send",
  COMMUNICATION_VIEW: "communication:view",

  // Materials permissions
  MATERIALS_VIEW: "materials:view",
  MATERIALS_UPLOAD: "materials:upload",
  MATERIALS_MANAGE: "materials:manage",
  TRACKS_VIEW: "tracks:view",
  TRACKS_MANAGE: "tracks:manage",

  // Call sheets
  CALLSHEETS_VIEW: "callsheets:view",
  CALLSHEETS_EDIT: "callsheets:edit",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// Organization role permissions mapping
export const ORGANIZATION_ROLE_PERMISSIONS: Record<OrganizationRole, Permission[]> = {
  owner: [
    PERMISSIONS.ORG_MANAGE_BILLING,
    PERMISSIONS.ORG_TRANSFER_OWNERSHIP,
    PERMISSIONS.ORG_MANAGE_MEMBERS,
    PERMISSIONS.ORG_MANAGE_SETTINGS,
    PERMISSIONS.ORG_CREATE_SHOWS,
    PERMISSIONS.ORG_VIEW_ALL_SHOWS,
    PERMISSIONS.ORG_DELETE_SHOWS,
    // Owners have all show permissions by default
    PERMISSIONS.SHOW_VIEW,
    PERMISSIONS.SHOW_EDIT,
    PERMISSIONS.SHOW_DELETE,
    PERMISSIONS.SHOW_MANAGE_STAFF,
    PERMISSIONS.CASTING_VIEW,
    PERMISSIONS.CASTING_EDIT,
    PERMISSIONS.CASTING_MAKE_DECISIONS,
    PERMISSIONS.AUDITIONS_VIEW,
    PERMISSIONS.AUDITIONS_EDIT,
    PERMISSIONS.AUDITIONS_MANAGE,
    PERMISSIONS.SCHEDULE_VIEW,
    PERMISSIONS.SCHEDULE_EDIT,
    PERMISSIONS.SCHEDULE_MANAGE,
    PERMISSIONS.NOTES_VIEW_ALL,
    PERMISSIONS.BUDGET_VIEW,
    PERMISSIONS.BUDGET_EDIT,
    PERMISSIONS.BUDGET_MANAGE,
    PERMISSIONS.COMMUNICATION_SEND,
    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.MATERIALS_VIEW,
    PERMISSIONS.MATERIALS_UPLOAD,
    PERMISSIONS.MATERIALS_MANAGE,
    PERMISSIONS.TRACKS_VIEW,
    PERMISSIONS.TRACKS_MANAGE,
    PERMISSIONS.CALLSHEETS_VIEW,
    PERMISSIONS.CALLSHEETS_EDIT,
  ],
  admin: [
    PERMISSIONS.ORG_MANAGE_MEMBERS,
    PERMISSIONS.ORG_MANAGE_SETTINGS,
    PERMISSIONS.ORG_CREATE_SHOWS,
    PERMISSIONS.ORG_VIEW_ALL_SHOWS,
    PERMISSIONS.ORG_DELETE_SHOWS,
    // Admins have all show permissions
    PERMISSIONS.SHOW_VIEW,
    PERMISSIONS.SHOW_EDIT,
    PERMISSIONS.SHOW_DELETE,
    PERMISSIONS.SHOW_MANAGE_STAFF,
    PERMISSIONS.CASTING_VIEW,
    PERMISSIONS.CASTING_EDIT,
    PERMISSIONS.CASTING_MAKE_DECISIONS,
    PERMISSIONS.AUDITIONS_VIEW,
    PERMISSIONS.AUDITIONS_EDIT,
    PERMISSIONS.AUDITIONS_MANAGE,
    PERMISSIONS.SCHEDULE_VIEW,
    PERMISSIONS.SCHEDULE_EDIT,
    PERMISSIONS.SCHEDULE_MANAGE,
    PERMISSIONS.NOTES_VIEW_ALL,
    PERMISSIONS.BUDGET_VIEW,
    PERMISSIONS.BUDGET_EDIT,
    PERMISSIONS.BUDGET_MANAGE,
    PERMISSIONS.COMMUNICATION_SEND,
    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.MATERIALS_VIEW,
    PERMISSIONS.MATERIALS_UPLOAD,
    PERMISSIONS.MATERIALS_MANAGE,
    PERMISSIONS.TRACKS_VIEW,
    PERMISSIONS.TRACKS_MANAGE,
    PERMISSIONS.CALLSHEETS_VIEW,
    PERMISSIONS.CALLSHEETS_EDIT,
  ],
  producer: [
    PERMISSIONS.ORG_CREATE_SHOWS,
    PERMISSIONS.ORG_VIEW_ALL_SHOWS,
    PERMISSIONS.SHOW_VIEW,
    PERMISSIONS.SHOW_EDIT,
    PERMISSIONS.SHOW_MANAGE_STAFF,
    PERMISSIONS.CASTING_VIEW,
    PERMISSIONS.CASTING_EDIT,
    PERMISSIONS.CASTING_MAKE_DECISIONS,
    PERMISSIONS.AUDITIONS_VIEW,
    PERMISSIONS.AUDITIONS_EDIT,
    PERMISSIONS.AUDITIONS_MANAGE,
    PERMISSIONS.SCHEDULE_VIEW,
    PERMISSIONS.SCHEDULE_EDIT,
    PERMISSIONS.SCHEDULE_MANAGE,
    PERMISSIONS.NOTES_VIEW_ALL,
    PERMISSIONS.BUDGET_VIEW,
    PERMISSIONS.BUDGET_EDIT,
    PERMISSIONS.BUDGET_MANAGE,
    PERMISSIONS.COMMUNICATION_SEND,
    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.MATERIALS_VIEW,
    PERMISSIONS.MATERIALS_UPLOAD,
    PERMISSIONS.MATERIALS_MANAGE,
    PERMISSIONS.TRACKS_VIEW,
    PERMISSIONS.TRACKS_MANAGE,
    PERMISSIONS.CALLSHEETS_VIEW,
    PERMISSIONS.CALLSHEETS_EDIT,
  ],
  associate_producer: [
    PERMISSIONS.ORG_VIEW_ALL_SHOWS,
    PERMISSIONS.SHOW_VIEW,
    PERMISSIONS.SHOW_EDIT,
    PERMISSIONS.CASTING_VIEW,
    PERMISSIONS.AUDITIONS_VIEW,
    PERMISSIONS.SCHEDULE_VIEW,
    PERMISSIONS.NOTES_VIEW_ALL,
    PERMISSIONS.BUDGET_VIEW,
    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.MATERIALS_VIEW,
    PERMISSIONS.TRACKS_VIEW,
    PERMISSIONS.CALLSHEETS_VIEW,
  ],
};

// Show role permissions mapping
export const SHOW_ROLE_PERMISSIONS: Record<ShowRole, Permission[]> = {
  director: [
    PERMISSIONS.SHOW_VIEW,
    PERMISSIONS.SHOW_EDIT,
    PERMISSIONS.SHOW_MANAGE_STAFF,
    PERMISSIONS.CASTING_VIEW,
    PERMISSIONS.CASTING_EDIT,
    PERMISSIONS.CASTING_MAKE_DECISIONS,
    PERMISSIONS.AUDITIONS_VIEW,
    PERMISSIONS.AUDITIONS_EDIT,
    PERMISSIONS.AUDITIONS_MANAGE,
    PERMISSIONS.SCHEDULE_VIEW,
    PERMISSIONS.SCHEDULE_EDIT,
    PERMISSIONS.NOTES_VIEW_ALL,
    PERMISSIONS.NOTES_PRODUCTION,
    PERMISSIONS.COMMUNICATION_SEND,
    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.MATERIALS_VIEW,
    PERMISSIONS.CALLSHEETS_VIEW,
    PERMISSIONS.CALLSHEETS_EDIT,
  ],
  music_director: [
    PERMISSIONS.SHOW_VIEW,
    PERMISSIONS.AUDITIONS_VIEW,
    PERMISSIONS.AUDITIONS_EDIT,
    PERMISSIONS.SCHEDULE_VIEW,
    PERMISSIONS.SCHEDULE_EDIT,
    PERMISSIONS.TRACKS_VIEW,
    PERMISSIONS.TRACKS_MANAGE,
    PERMISSIONS.MATERIALS_VIEW,
    PERMISSIONS.CALLSHEETS_VIEW,
  ],
  choreographer: [
    PERMISSIONS.SHOW_VIEW,
    PERMISSIONS.AUDITIONS_VIEW,
    PERMISSIONS.AUDITIONS_EDIT,
    PERMISSIONS.SCHEDULE_VIEW,
    PERMISSIONS.SCHEDULE_EDIT,
    PERMISSIONS.NOTES_CHOREOGRAPHY,
    PERMISSIONS.MATERIALS_VIEW,
    PERMISSIONS.CALLSHEETS_VIEW,
  ],
  stage_manager: [
    PERMISSIONS.SHOW_VIEW,
    PERMISSIONS.SCHEDULE_VIEW,
    PERMISSIONS.SCHEDULE_EDIT,
    PERMISSIONS.SCHEDULE_MANAGE,
    PERMISSIONS.NOTES_VIEW_ALL,
    PERMISSIONS.NOTES_PRODUCTION,
    PERMISSIONS.COMMUNICATION_SEND,
    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.CALLSHEETS_VIEW,
    PERMISSIONS.CALLSHEETS_EDIT,
    PERMISSIONS.MATERIALS_VIEW,
  ],
  assistant_stage_manager: [
    PERMISSIONS.SHOW_VIEW,
    PERMISSIONS.SCHEDULE_VIEW,
    PERMISSIONS.SCHEDULE_EDIT,
    PERMISSIONS.CALLSHEETS_VIEW,
    PERMISSIONS.CALLSHEETS_EDIT,
    PERMISSIONS.MATERIALS_VIEW,
  ],
  production_manager: [
    PERMISSIONS.SHOW_VIEW,
    PERMISSIONS.SCHEDULE_VIEW,
    PERMISSIONS.SCHEDULE_EDIT,
    PERMISSIONS.BUDGET_VIEW,
    PERMISSIONS.BUDGET_EDIT,
    PERMISSIONS.BUDGET_MANAGE,
    PERMISSIONS.MATERIALS_VIEW,
    PERMISSIONS.CALLSHEETS_VIEW,
  ],
  technical_director: [
    PERMISSIONS.SHOW_VIEW,
    PERMISSIONS.SCHEDULE_VIEW,
    PERMISSIONS.SCHEDULE_EDIT,
    PERMISSIONS.NOTES_SCENIC,
    PERMISSIONS.NOTES_LIGHTING,
    PERMISSIONS.MATERIALS_VIEW,
    PERMISSIONS.CALLSHEETS_VIEW,
  ],
  lighting_designer: [
    PERMISSIONS.SHOW_VIEW,
    PERMISSIONS.SCHEDULE_VIEW,
    PERMISSIONS.NOTES_LIGHTING,
    PERMISSIONS.MATERIALS_VIEW,
    PERMISSIONS.CALLSHEETS_VIEW,
  ],
  sound_designer: [
    PERMISSIONS.SHOW_VIEW,
    PERMISSIONS.SCHEDULE_VIEW,
    PERMISSIONS.NOTES_SOUND,
    PERMISSIONS.TRACKS_VIEW,
    PERMISSIONS.TRACKS_MANAGE,
    PERMISSIONS.MATERIALS_VIEW,
    PERMISSIONS.CALLSHEETS_VIEW,
  ],
  costume_designer: [
    PERMISSIONS.SHOW_VIEW,
    PERMISSIONS.SCHEDULE_VIEW,
    PERMISSIONS.NOTES_COSTUME,
    PERMISSIONS.MATERIALS_VIEW,
    PERMISSIONS.CALLSHEETS_VIEW,
  ],
  scenic_designer: [
    PERMISSIONS.SHOW_VIEW,
    PERMISSIONS.SCHEDULE_VIEW,
    PERMISSIONS.NOTES_SCENIC,
    PERMISSIONS.MATERIALS_VIEW,
    PERMISSIONS.CALLSHEETS_VIEW,
  ],
  props_master: [
    PERMISSIONS.SHOW_VIEW,
    PERMISSIONS.SCHEDULE_VIEW,
    PERMISSIONS.NOTES_PROPS,
    PERMISSIONS.BUDGET_PROPS,
    PERMISSIONS.MATERIALS_VIEW,
    PERMISSIONS.CALLSHEETS_VIEW,
  ],
  hair_makeup_designer: [
    PERMISSIONS.SHOW_VIEW,
    PERMISSIONS.SCHEDULE_VIEW,
    PERMISSIONS.NOTES_HAIR_MAKEUP,
    PERMISSIONS.MATERIALS_VIEW,
    PERMISSIONS.CALLSHEETS_VIEW,
  ],
  dramaturg: [
    PERMISSIONS.SHOW_VIEW,
    PERMISSIONS.NOTES_DRAMATURG,
    PERMISSIONS.COMMUNICATION_SEND,
    PERMISSIONS.COMMUNICATION_VIEW,
    PERMISSIONS.MATERIALS_VIEW,
    PERMISSIONS.CALLSHEETS_VIEW,
  ],
  assistant_director: [
    PERMISSIONS.SHOW_VIEW,
    PERMISSIONS.SCHEDULE_VIEW,
    PERMISSIONS.NOTES_AD,
    PERMISSIONS.MATERIALS_VIEW,
    PERMISSIONS.CALLSHEETS_VIEW,
  ],
  crew_member: [PERMISSIONS.SHOW_VIEW, PERMISSIONS.SCHEDULE_VIEW, PERMISSIONS.CALLSHEETS_VIEW],
};

// Permission check result
export interface PermissionCheckResult {
  allowed: boolean;
  reason?: string;
  role?: OrganizationRole | ShowRole;
}

// User permissions context
export interface UserPermissionsContext {
  userId: string;
  organizationId?: string;
  organizationRole?: OrganizationRole;
  showId?: string;
  showRole?: ShowRole;
  permissions: Permission[];
}
